apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: sugesh23/springboot:latest  
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: app
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-0.mysql-headless:3306/challenge?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_WRITER_URL
              value: jdbc:mysql://mysql-0.mysql-headless:3306/challenge?createDatabaseIfNotExist=true
            - name: ACTUATOR_ENDPOINTS
              value: health,info,prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer